export interface HeadquartersFeature {
  id: string;
  name: string;
  shortName: string;
  category: "railway_hq" | "geo_institute" | "resource_hq" | "port_authority" | "meteorological_hq";
  categoryLabel: string;
  city: string;
  state: string;
  coordinates: [number, number]; // [lat, lng]
  establishedYear: number;
  parentMinistryOrBody: string;
  significance: string;
  ncertChapterRef: string;
  classGrade: "11" | "12" | "both";
  cbseExamRelevance: string;
  jurisdictionOrScope: string;
  color: string;
  icon: string;
}

export const HEADQUARTERS_DATA: HeadquartersFeature[] = [
  // ------------------------------------------------------------------------
  // 1. CBSE CLASS 12 RAILWAY ZONE HEADQUARTERS (NCERT Transport & Comm)
  // ------------------------------------------------------------------------
  {
    id: "hq-rail-nr",
    name: "Northern Railway Headquarters",
    shortName: "NR - New Delhi",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "New Delhi",
    state: "Delhi",
    coordinates: [28.6448, 77.2167],
    establishedYear: 1952,
    parentMinistryOrBody: "Ministry of Railways, Government of India",
    significance: "Largest railway zone in India by route kilometers. Originates the prestigious Rajdhani, Shatabdi, and Vande Bharat corridors connecting the capital with northern and eastern India.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7: Transport and Communication",
    classGrade: "12",
    cbseExamRelevance: "Guaranteed Board Exam map question: Identify or plot Northern Railway HQ (New Delhi).",
    jurisdictionOrScope: "Delhi, Haryana, Punjab, Himachal Pradesh, Jammu & Kashmir, and Western Uttar Pradesh",
    color: "#38bdf8",
    icon: "🚆",
  },
  {
    id: "hq-rail-wr",
    name: "Western Railway Headquarters (Churchgate)",
    shortName: "WR - Mumbai Churchgate",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Mumbai",
    state: "Maharashtra",
    coordinates: [18.9352, 72.8277],
    establishedYear: 1951,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Headquartered at historic Churchgate building. Operates the suburban railway lifeline of Mumbai and heavy freight corridors from ports of Gujarat (Kandla, Mundra) to north India.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Often tested alongside Central Railway HQ (both in Mumbai: Churchgate vs CSMT).",
    jurisdictionOrScope: "Western Maharashtra, Gujarat, parts of Western MP and Southern Rajasthan",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-cr",
    name: "Central Railway Headquarters (CSMT)",
    shortName: "CR - Mumbai CSMT",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Mumbai",
    state: "Maharashtra",
    coordinates: [18.9400, 72.8353],
    establishedYear: 1951,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Housed in the UNESCO World Heritage Chhatrapati Shivaji Maharaj Terminus (formerly Victoria Terminus), pioneer of the first passenger train in India (1853, Mumbai to Thane, 34 km).",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "NCERT Box question: Date and route of first train in India (16 April 1853, Boribunder to Thane).",
    jurisdictionOrScope: "Maharashtra, parts of Madhya Pradesh and Karnataka",
    color: "#0369a1",
    icon: "🚆",
  },
  {
    id: "hq-rail-er",
    name: "Eastern Railway Headquarters (Fairlie Place)",
    shortName: "ER - Kolkata",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Kolkata",
    state: "West Bengal",
    coordinates: [22.5726, 88.3475],
    establishedYear: 1952,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Covers the mineral and coal-rich industrial belts of eastern India, serving the Howrah and Sealdah hubs.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "High exam frequency: Plot Eastern Railway HQ at Kolkata.",
    jurisdictionOrScope: "West Bengal, parts of Bihar and Jharkhand",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-sr",
    name: "Southern Railway Headquarters (Park Town)",
    shortName: "SR - Chennai",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Chennai",
    state: "Tamil Nadu",
    coordinates: [13.0827, 80.2707],
    establishedYear: 1951,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "First railway zone created in independent India (14 April 1951) by merging Madras and Southern Mahratta, South Indian, and Mysore State Railways.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Key peninsular railway hub tested in CBSE Class 12 board map skills.",
    jurisdictionOrScope: "Tamil Nadu, Kerala, Puducherry, and small parts of Andhra Pradesh",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-scr",
    name: "South Central Railway Headquarters (Rail Nilayam)",
    shortName: "SCR - Secunderabad",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Secunderabad / Hyderabad",
    state: "Telangana",
    coordinates: [17.4399, 78.5017],
    establishedYear: 1966,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Crucial north-south transit bridge across the Deccan plateau linking peninsular ports with industrial inland centers.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Very frequent question: HQ of South Central Railway is Secunderabad.",
    jurisdictionOrScope: "Telangana, Andhra Pradesh, parts of Maharashtra and Karnataka",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-ecor",
    name: "East Coast Railway Headquarters",
    shortName: "ECoR - Bhubaneswar",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Bhubaneswar",
    state: "Odisha",
    coordinates: [20.2961, 85.8245],
    establishedYear: 2003,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Handles the highest volume of mineral freight loading in Indian Railways (iron ore from Bailadila and Keonjhar, coal from Talcher to Paradip and Vizag ports).",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Linked with mineral freight transport questions in CBSE 12.",
    jurisdictionOrScope: "Odisha, parts of northeastern Andhra Pradesh and southern Chhattisgarh",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-nwr",
    name: "North Western Railway Headquarters",
    shortName: "NWR - Jaipur",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Jaipur",
    state: "Rajasthan",
    coordinates: [26.9124, 75.7873],
    establishedYear: 2002,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Covers the arid and semi-arid terrain of Rajasthan and the Delhi-Mumbai freight corridor route.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Board map practice: HQ of North Western Railway at Jaipur.",
    jurisdictionOrScope: "Rajasthan, parts of Haryana and Punjab",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-ner",
    name: "North Eastern Railway Headquarters",
    shortName: "NER - Gorakhpur",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Gorakhpur",
    state: "Uttar Pradesh",
    coordinates: [26.7606, 83.3732],
    establishedYear: 1952,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Houses one of the longest railway platforms in the world (1,366 m). Vital for Terai border trade with Nepal.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Commonly confused with Northeast Frontier (Guwahati). Remind: NER is Gorakhpur.",
    jurisdictionOrScope: "Eastern Uttar Pradesh, Western Bihar, Uttarakhand Terai",
    color: "#0284c7",
    icon: "🚆",
  },
  {
    id: "hq-rail-nfr",
    name: "Northeast Frontier Railway Headquarters (Maligaon)",
    shortName: "NFR - Guwahati (Maligaon)",
    category: "railway_hq",
    categoryLabel: "Railway Zone HQ",
    city: "Guwahati",
    state: "Assam",
    coordinates: [26.1558, 91.6883],
    establishedYear: 1958,
    parentMinistryOrBody: "Ministry of Railways",
    significance: "Connects the strategic 'Seven Sister States' via the narrow Siliguri Corridor ('Chicken's Neck'). Operates the UNESCO Darjeeling Himalayan Toy Train.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7",
    classGrade: "12",
    cbseExamRelevance: "Strategic geography question: Northeast Frontier Railway HQ at Guwahati.",
    jurisdictionOrScope: "All 8 Northeastern States, Northern West Bengal, parts of Bihar",
    color: "#0284c7",
    icon: "🚆",
  },

  // ------------------------------------------------------------------------
  // 2. NATIONAL GEOGRAPHY, EARTH SCIENCE & CARTOGRAPHY INSTITUTES
  // ------------------------------------------------------------------------
  {
    id: "hq-inst-soi",
    name: "Survey of India (National Mapping Agency)",
    shortName: "Survey of India - Dehradun",
    category: "geo_institute",
    categoryLabel: "National Mapping & Cartography",
    city: "Dehradun",
    state: "Uttarakhand",
    coordinates: [30.3398, 78.0489],
    establishedYear: 1767,
    parentMinistryOrBody: "Department of Science and Technology (DST)",
    significance: "Oldest scientific department of the Government of India (founded under Major James Rennell). Responsible for all official topographical sheet series (1:50,000 & 1:25,000) studied in CBSE Class 11 Practical Geography.",
    ncertChapterRef: "Class 11 - Practical Work in Geography, Ch 1: Introduction to Maps & Ch 5: Topographical Maps",
    classGrade: "11",
    cbseExamRelevance: "Direct Practical Exam question: Toposheets are surveyed and published under the direction of the Surveyor General of India, Dehradun.",
    jurisdictionOrScope: "National Geodetic Reference Frame, international border demarcations, standard toposheet mapping of India",
    color: "#10b981",
    icon: "🗺️",
  },
  {
    id: "hq-inst-gsi",
    name: "Geological Survey of India (GSI)",
    shortName: "GSI - Kolkata",
    category: "geo_institute",
    categoryLabel: "Geological & Mineral Survey",
    city: "Kolkata",
    state: "West Bengal",
    coordinates: [22.5601, 88.3512],
    establishedYear: 1851,
    parentMinistryOrBody: "Ministry of Mines, Government of India",
    significance: "Pioneering geoscience organization (created by Dr. Thomas Oldham). Discovered and systematically mapped India's Gondwana coalfields, Deccan basalts, and Himalayan orogenic belts.",
    ncertChapterRef: "Class 11 - Fundamentals of Physical Geography, Ch 4 & Class 12 Ch 5",
    classGrade: "both",
    cbseExamRelevance: "Vital agency credited in NCERT for geological time scale and mineral inventory data.",
    jurisdictionOrScope: "All geological mapping, marine mineral research, landslide warning, seismic hazard microzonation in India",
    color: "#10b981",
    icon: "⛏️",
  },
  {
    id: "hq-inst-imd",
    name: "India Meteorological Department (Mausam Bhawan)",
    shortName: "IMD - New Delhi",
    category: "meteorological_hq",
    categoryLabel: "Meteorological & Weather Monitoring",
    city: "New Delhi",
    state: "Delhi",
    coordinates: [28.5898, 77.2223],
    establishedYear: 1875,
    parentMinistryOrBody: "Ministry of Earth Sciences (MoES)",
    significance: "Official weather agency responsible for publishing Daily Weather Maps (studied in Class 11 Practical), monitoring the Southwest Monsoon onset, tracking tropical cyclones, and measuring rainfall.",
    ncertChapterRef: "Class 11 - India: Physical Environment, Ch 4: Climate & Practical Ch 8: Weather Instruments",
    classGrade: "11",
    cbseExamRelevance: "Practical geography syllabus: Daily weather charts (isobars, wind feathers, isotherms) are published by IMD.",
    jurisdictionOrScope: "Pan-India meteorological observatories, Doppler weather radars, INSAT satellite meteorology",
    color: "#06b6d4",
    icon: "⛅",
  },
  {
    id: "hq-inst-fsi",
    name: "Forest Survey of India (FSI)",
    shortName: "FSI - Dehradun",
    category: "geo_institute",
    categoryLabel: "Forest & Remote Sensing Assessment",
    city: "Dehradun",
    state: "Uttarakhand",
    coordinates: [30.3421, 78.0062],
    establishedYear: 1981,
    parentMinistryOrBody: "Ministry of Environment, Forest and Climate Change (MoEFCC)",
    significance: "Publishes the biennial 'India State of Forest Report' (ISFR) tracking national forest cover targets (33% National Forest Policy goal vs current ~24.6%).",
    ncertChapterRef: "Class 11 - India: Physical Environment, Ch 5: Natural Vegetation",
    classGrade: "11",
    cbseExamRelevance: "Cited in CBSE 11 for Forest Cover percentages and Mangrove distribution data.",
    jurisdictionOrScope: "Forest canopy density mapping, forest fire alert systems, carbon stock assessment",
    color: "#10b981",
    icon: "🌲",
  },
  {
    id: "hq-inst-cazri",
    name: "Central Arid Zone Research Institute (CAZRI)",
    shortName: "CAZRI - Jodhpur",
    category: "geo_institute",
    categoryLabel: "Arid Ecosystem & Desertification Control",
    city: "Jodhpur",
    state: "Rajasthan",
    coordinates: [26.2625, 73.0189],
    establishedYear: 1959,
    parentMinistryOrBody: "Indian Council of Agricultural Research (ICAR)",
    significance: "World-renowned institute dedicated to combating desertification in the Thar Desert. Developed sand dune stabilization methods and drought-resistant crops (Khejri, Ber, Bajra).",
    ncertChapterRef: "Class 11 - India: Physical Environment, Ch 6: Soils & Ch 7: Natural Hazards",
    classGrade: "11",
    cbseExamRelevance: "Frequently discussed in Soil Conservation and Desertification prevention techniques.",
    jurisdictionOrScope: "Hot arid regions of Rajasthan, Gujarat, Punjab, Haryana and cold arid areas of Ladakh",
    color: "#eab308",
    icon: "🏜️",
  },
  {
    id: "hq-inst-nrsc",
    name: "National Remote Sensing Centre (NRSC / ISRO)",
    shortName: "NRSC (ISRO) - Hyderabad",
    category: "geo_institute",
    categoryLabel: "Space Geoinformatics & Remote Sensing",
    city: "Hyderabad (Balanagar & Shadnagar)",
    state: "Telangana",
    coordinates: [17.4721, 78.4419],
    establishedYear: 1974,
    parentMinistryOrBody: "Department of Space (ISRO)",
    significance: "Houses satellite ground stations acquiring data from Resourcesat, Cartosat, and Oceansat. Manages India's geoportal 'Bhuvan' studied in Geo-informatics chapters.",
    ncertChapterRef: "Class 11 - Practical Work, Ch 6: Introduction to Aerial Photographs & Ch 7: Remote Sensing",
    classGrade: "both",
    cbseExamRelevance: "Key practical chapter: Applications of remote sensing and GIS in flood forecasting and land use mapping.",
    jurisdictionOrScope: "Satellite payload data reception, earth observation applications, disaster support services",
    color: "#8b5cf6",
    icon: "🛰️",
  },
  {
    id: "hq-inst-icar",
    name: "Indian Council of Agricultural Research (Krishi Bhawan)",
    shortName: "ICAR - New Delhi",
    category: "resource_hq",
    categoryLabel: "Agricultural & Soil Classification",
    city: "New Delhi",
    state: "Delhi",
    coordinates: [28.6186, 77.2144],
    establishedYear: 1929,
    parentMinistryOrBody: "Ministry of Agriculture and Farmers Welfare",
    significance: "Apex body that formulated the official 8-fold classification of Indian Soils (Alluvial, Black/Regur, Red & Yellow, Laterite, Arid, Saline, Peaty, Forest) taught in NCERT.",
    ncertChapterRef: "Class 11 - India: Physical Environment, Ch 6: Soils",
    classGrade: "11",
    cbseExamRelevance: "Standard question in CBSE 11: Identify the ICAR classification of soils of India.",
    jurisdictionOrScope: "National coordination of agricultural research, soil survey (NBSS&LUP), dryland farming",
    color: "#16a34a",
    icon: "🌾",
  },
  {
    id: "hq-inst-iwai",
    name: "Inland Waterways Authority of India (IWAI)",
    shortName: "IWAI - Noida",
    category: "resource_hq",
    categoryLabel: "National Waterways & Navigation",
    city: "Noida",
    state: "Uttar Pradesh",
    coordinates: [28.5833, 77.3167],
    establishedYear: 1986,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Manages National Waterways including NW-1 (Ganga: Prayagraj to Haldia, 1620 km), NW-2 (Brahmaputra: Sadiya to Dhubri, 891 km), and NW-3 (Kottapuram to Kollam, 205 km).",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 7: Transport and Communication",
    classGrade: "12",
    cbseExamRelevance: "CBSE Board Exam Map question: Plot NW-1 (Prayagraj-Haldia) and NW-2 (Sadiya-Dhubri).",
    jurisdictionOrScope: "Development of National Waterways, multi-modal terminals (Varanasi, Sahibganj, Haldia)",
    color: "#0891b2",
    icon: "🚢",
  },

  // ------------------------------------------------------------------------
  // 3. KEY RESOURCE, MINERAL & INDUSTRIAL HEADQUARTERS
  // ------------------------------------------------------------------------
  {
    id: "hq-res-cil",
    name: "Coal India Limited (CIL - Coal Bhawan)",
    shortName: "Coal India - Kolkata",
    category: "resource_hq",
    categoryLabel: "Energy & Coal Resources",
    city: "Kolkata (New Town)",
    state: "West Bengal",
    coordinates: [22.5855, 88.4682],
    establishedYear: 1975,
    parentMinistryOrBody: "Ministry of Coal",
    significance: "World's largest government-owned coal producer, producing over 80% of India's commercial coal from Gondwana basins (Damodar, Mahanadi, Son, Godavari valleys).",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 5: Mineral and Energy Resources",
    classGrade: "12",
    cbseExamRelevance: "Linked with coalfield mapping: Jharia, Raniganj, Bokaro, Singrauli, Korba, Talcher.",
    jurisdictionOrScope: "Eight subsidiaries covering major coalfields across Jharkhand, West Bengal, MP, Chhattisgarh, Odisha, Maharashtra",
    color: "#475569",
    icon: "🪨",
  },
  {
    id: "hq-res-ongc",
    name: "Oil and Natural Gas Corporation (Tel Bhawan)",
    shortName: "ONGC - Dehradun / New Delhi",
    category: "resource_hq",
    categoryLabel: "Hydrocarbon Exploration & Production",
    city: "Dehradun (Registered) / New Delhi (Corp)",
    state: "Uttarakhand / Delhi",
    coordinates: [30.3256, 78.0264],
    establishedYear: 1956,
    parentMinistryOrBody: "Ministry of Petroleum and Natural Gas",
    significance: "Produces ~70% of India's domestic crude oil. Discovered offshore Mumbai High in 1974 and operates onshore fields in Cambay basin (Ankleshwar) and Assam (Digboi/Moran).",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 5: Mineral and Energy Resources",
    classGrade: "12",
    cbseExamRelevance: "Compulsory map question: Locate Mumbai High offshore oil field and Ankleshwar.",
    jurisdictionOrScope: "Domestic onshore and deepwater offshore exploration in Krishna-Godavari, Cambay, Mumbai Offshore, Assam-Arakan basins",
    color: "#dc2626",
    icon: "🛢️",
  },
  {
    id: "hq-res-sail",
    name: "Steel Authority of India Limited (Ispat Bhawan)",
    shortName: "SAIL - New Delhi",
    category: "resource_hq",
    categoryLabel: "Metallurgical & Steel Industry",
    city: "New Delhi (Lodhi Road)",
    state: "Delhi",
    coordinates: [28.5912, 77.2289],
    establishedYear: 1973,
    parentMinistryOrBody: "Ministry of Steel",
    significance: "Operates five integrated steel plants located strategically close to iron ore, coal, and limestone sources: Bhilai (Chhattisgarh), Rourkela (Odisha), Durgapur (West Bengal), Bokaro (Jharkhand), and Burnpur.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 6: Manufacturing Industries",
    classGrade: "12",
    cbseExamRelevance: "CBSE Board map pointing favorites: Bhilai (Durg), Rourkela (Sundargarh), Bokaro.",
    jurisdictionOrScope: "Chota Nagpur and adjoining mineral-rich iron ore belts",
    color: "#ea580c",
    icon: "🏭",
  },

  // ------------------------------------------------------------------------
  // 4. MAJOR PORT AUTHORITIES (Class 12 International Trade)
  // ------------------------------------------------------------------------
  {
    id: "hq-port-kandla",
    name: "Deendayal Port Authority (Kandla)",
    shortName: "Kandla Port Authority - Gandhidham",
    category: "port_authority",
    categoryLabel: "Major Port Authority",
    city: "Gandhidham / Kandla",
    state: "Gujarat",
    coordinates: [23.0033, 70.2181],
    establishedYear: 1950,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Tidal port built to serve the vast northwestern agricultural and industrial hinterland (Punjab, Haryana, Rajasthan, Gujarat) following the loss of Karachi port after Partition.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    classGrade: "12",
    cbseExamRelevance: "Top frequent map question in CBSE 12: Locate Kandla tidal port on Gujarat coast.",
    jurisdictionOrScope: "Handles crude oil, petroleum products, fertilizers, grains, salt exports",
    color: "#059669",
    icon: "⚓",
  },
  {
    id: "hq-port-jnpa",
    name: "Jawaharlal Nehru Port Authority (JNPA / Nhava Sheva)",
    shortName: "JNPA - Navi Mumbai",
    category: "port_authority",
    categoryLabel: "Major Port Authority",
    city: "Navi Mumbai",
    state: "Maharashtra",
    coordinates: [18.9496, 72.9515],
    establishedYear: 1989,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Premier container handling port of India handling over 50% of the country's containerized cargo. Built as a modern satellite port to decongest Mumbai Port.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    classGrade: "12",
    cbseExamRelevance: "Board Exam distinction: Mumbai Port is a natural deep harbour; JNPT is India's largest container port.",
    jurisdictionOrScope: "Western and Northern India container export-import corridor",
    color: "#059669",
    icon: "⚓",
  },
  {
    id: "hq-port-vizag",
    name: "Visakhapatnam Port Authority",
    shortName: "Vizag Port Authority - Visakhapatnam",
    category: "port_authority",
    categoryLabel: "Major Port Authority",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    coordinates: [17.6868, 83.2185],
    establishedYear: 1933,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Deepest landlocked, protected natural harbour on the east coast formed by Dolphin's Nose hill. Developed specially to export Bailadila iron ore to Japan.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    classGrade: "12",
    cbseExamRelevance: "Classic CBSE question: Name the port developed to export Bailadila iron ore (Visakhapatnam).",
    jurisdictionOrScope: "Andhra Pradesh, Telangana, southern Odisha, eastern Chhattisgarh hinterland",
    color: "#059669",
    icon: "⚓",
  },
  {
    id: "hq-port-smp",
    name: "Syama Prasad Mookerjee Port Authority (Kolkata Port)",
    shortName: "Kolkata Port Authority - Kolkata",
    category: "port_authority",
    categoryLabel: "Major Port Authority",
    city: "Kolkata / Haldia",
    state: "West Bengal",
    coordinates: [22.5447, 88.3186],
    establishedYear: 1870,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Only major riverine port in India, located 128 km from the sea on the left bank of the Hooghly River. Suffers from siltation and tidal bores; assisted by Haldia satellite dock downstream.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    classGrade: "12",
    cbseExamRelevance: "CBSE favorite: Only major riverine port in India (Kolkata Port).",
    jurisdictionOrScope: "Serves landlocked neighbors Nepal and Bhutan, plus entire Eastern and Northeastern India",
    color: "#059669",
    icon: "⚓",
  },
  {
    id: "hq-port-cochin",
    name: "Cochin Port Authority (Willingdon Island)",
    shortName: "Cochin Port Authority - Kochi",
    category: "port_authority",
    categoryLabel: "Major Port Authority",
    city: "Kochi",
    state: "Kerala",
    coordinates: [9.9667, 76.2667],
    establishedYear: 1928,
    parentMinistryOrBody: "Ministry of Ports, Shipping and Waterways",
    significance: "Natural harbour at the mouth of Vembanad Lake, nicknamed the 'Queen of the Arabian Sea'. Located closest to international maritime shipping routes passing through Indian Ocean.",
    ncertChapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    classGrade: "12",
    cbseExamRelevance: "CBSE Board question: Port situated at the head of Vembanad Kayal (Kochi Port).",
    jurisdictionOrScope: "Kerala, southwestern Tamil Nadu, Karnataka plantation exports (spices, tea, coffee)",
    color: "#059669",
    icon: "⚓",
  },
];
