export const INITIAL_USERS = [
  {
    id: "user-aarav-11",
    name: "Aarav Sharma",
    email: "aarav.sharma@cbse.student.in",
    password: "password123",
    role: "student",
    classGrade: "11",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    schoolName: "Delhi Public School, R.K. Puram",
  },
  {
    id: "user-priya-12",
    name: "Priya Nair",
    email: "priya.nair@cbse.student.in",
    password: "password123",
    role: "student",
    classGrade: "12",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    schoolName: "Kendriya Vidyalaya, IIT Powai",
  },
  {
    id: "user-teacher-rao",
    name: "Dr. Sunita Rao (Senior Geography Faculty)",
    email: "sunita.rao@kv.gov.in",
    password: "password123",
    role: "teacher",
    classGrade: "11",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    schoolName: "Kendriya Vidyalaya Sangathan",
  },
];

export const INITIAL_ANNOTATIONS = [
  {
    id: "annot-1",
    userId: "user-aarav-11",
    title: "Indus Gorge at Nanga Parbat",
    description: "Deepest gorge in the world (approx 5,200m). Demonstrates antecedent river drainage cutting through rising Himalayan orogeny.",
    category: "rivers",
    latitude: "35.2375",
    longitude: "74.5891",
    elevation: "5,200m gorge depth / 8,126m peak",
    classGrade: "11",
    chapterRef: "Class 11 - India: Physical Environment, Ch 3: Drainage System",
    markerColor: "#0284c7",
    tags: ["Indus", "Antecedent River", "Himalayan Drainage", "NCERT Ch 3"],
    isShared: true,
  },
  {
    id: "annot-2",
    userId: "user-aarav-11",
    title: "Deccan Traps & Regur (Black) Soil",
    description: "Formed by Cretaceous fissure volcanic eruptions. Rich in iron, magnesia, and alumina. Highly clayey with deep cracks during dry season (self-ploughing effect).",
    category: "soils",
    latitude: "19.7515",
    longitude: "75.7139",
    elevation: "600m",
    classGrade: "11",
    chapterRef: "Class 11 - India: Physical Environment, Ch 6: Soils",
    markerColor: "#1e293b",
    tags: ["Black Soil", "Regur", "Cotton Soil", "Basalt", "NCERT Ch 6"],
    isShared: true,
  },
  {
    id: "annot-3",
    userId: "user-aarav-11",
    title: "Mid-Atlantic Ridge - Divergent Boundary",
    description: "Submarine mountain system formed by plate divergence where North American and Eurasian plates pull apart. Upwelling basaltic magma creates new oceanic crust.",
    category: "tectonics",
    latitude: "25.0000",
    longitude: "-45.0000",
    elevation: "-2,500m (underwater)",
    classGrade: "11",
    chapterRef: "Class 11 - Fundamentals of Physical Geography, Ch 4: Plate Tectonics",
    markerColor: "#dc2626",
    tags: ["Divergent Plate Boundary", "Sea Floor Spreading", "Mid-Atlantic Ridge"],
    isShared: true,
  },
  {
    id: "annot-4",
    userId: "user-priya-12",
    title: "Bailadila Iron Ore Mine (Bastar)",
    description: "High-grade haematite ore. Ore transported via slurry pipeline to Visakhapatnam port for export to Japan and South Korea. Key map item in CBSE 12.",
    category: "minerals",
    latitude: "18.6667",
    longitude: "81.2500",
    elevation: "1,200m",
    classGrade: "12",
    chapterRef: "Class 12 - India: People and Economy, Ch 5: Mineral and Energy Resources",
    markerColor: "#d97706",
    tags: ["Iron Ore", "Bailadila", "Chhattisgarh", "CBSE 12 Board Map"],
    isShared: true,
  },
  {
    id: "annot-5",
    userId: "user-priya-12",
    title: "Kandla (Deendayal) Port - Gulf of Kachchh",
    description: "Tidal port developed after partition to relieve pressure on Mumbai port. Caters to the hinterland of Punjab, Haryana, Rajasthan, and Gujarat.",
    category: "ports",
    latitude: "23.0033",
    longitude: "70.2181",
    elevation: "3m",
    classGrade: "12",
    chapterRef: "Class 12 - India: People and Economy, Ch 8: International Trade",
    markerColor: "#059669",
    tags: ["Tidal Port", "Major Port", "Gujarat", "CBSE 12 Board Map"],
    isShared: true,
  },
  {
    id: "annot-6",
    userId: "user-aarav-11",
    title: "Anamudi Peak - Western Ghats",
    description: "Highest peak in South India (2,695m) located in the Anaimalai Hills. Acts as a prominent water divide and orographic barrier for the Southwest Monsoon.",
    category: "mountains",
    latitude: "10.1699",
    longitude: "77.0641",
    elevation: "2,695m",
    classGrade: "11",
    chapterRef: "Class 11 - India: Physical Environment, Ch 2: Physiography",
    markerColor: "#15803d",
    tags: ["Anamudi", "Western Ghats", "Highest Peak of Peninsular India", "NCERT Ch 2"],
    isShared: true,
  },
];

export const INITIAL_QUIZZES = [
  {
    id: "quiz-class11-phys",
    userId: "user-teacher-rao",
    title: "CBSE Class 11: Indian Physiography & Drainage Master Quiz",
    description: "Test your spatial recognition of major rivers, mountain passes, peaks, and soil zones as mandated by NCERT Class XI Syllabus.",
    classGrade: "11",
    chapterRef: "Class 11 - India: Physical Environment, Ch 2 & 3",
    difficulty: "medium",
    isOfficial: true,
    questions: [
      {
        id: "q1",
        prompt: "Which of the following rivers is an antecedent river cutting through the Greater Himalayas via a stupendous gorge?",
        options: ["Ganga", "Indus", "Yamuna", "Godavari"],
        correctAnswer: "Indus",
        targetCoords: { lat: 35.2375, lng: 74.5891 },
        explanation: "Indus, Sutlej, and Brahmaputra existed before the Himalayas were folded and kept cutting down their channels as the mountains rose.",
      },
      {
        id: "q2",
        prompt: "Identify the highest peak of Peninsular India located at the junction of Anaimalai, Palani, and Cardamom Hills.",
        options: ["Doda Betta (2,637 m)", "Anamudi (2,695 m)", "Mahendragiri (1,501 m)", "Guru Shikhar (1,722 m)"],
        correctAnswer: "Anamudi (2,695 m)",
        targetCoords: { lat: 10.1699, lng: 77.0641 },
        explanation: "Anamudi (2,695m) in Kerala is the highest peak in South India and the Western Ghats.",
      },
      {
        id: "q3",
        prompt: "Which soil order is characterized by 'self-ploughing' characteristics due to high clay content and swelling when wet?",
        options: ["Alluvial Soil", "Laterite Soil", "Black / Regur Soil", "Arid Soil"],
        correctAnswer: "Black / Regur Soil",
        targetCoords: { lat: 19.7515, lng: 75.7139 },
        explanation: "Black soil develops deep wide cracks during dry periods which causes self-aeration and ploughing.",
      },
      {
        id: "q4",
        prompt: "Which rift valley in India is occupied by a west-flowing peninsular river flowing between Vindhya and Satpura ranges?",
        options: ["Godavari Valley", "Narmada Valley", "Mahanadi Valley", "Damodar Valley"],
        correctAnswer: "Narmada Valley",
        targetCoords: { lat: 21.8000, lng: 76.5000 },
        explanation: "The Narmada originates from Amarkantak plateau and flows west through a structural rift valley between Vindhya (north) and Satpura (south).",
      },
      {
        id: "q5",
        prompt: "What is the boundary between the Pacific Plate and the North American Plate along western California known as?",
        options: ["Mid-Atlantic Ridge", "San Andreas Fault", "Mariana Trench", "Java Trench"],
        correctAnswer: "San Andreas Fault",
        targetCoords: { lat: 35.1200, lng: -119.5500 },
        explanation: "The San Andreas Fault is a classic transform fault boundary where plates slide past each other horizontally.",
      },
    ],
  },
  {
    id: "quiz-class12-board",
    userId: "user-teacher-rao",
    title: "CBSE Class 12: Board Exam Map Skills & Economic Geography",
    description: "Compulsory map pointing questions for CBSE Class 12 Board Exam: Ports, Mineral belts, Coalfields, and Oil refineries.",
    classGrade: "12",
    chapterRef: "Class 12 - India: People and Economy, Ch 5 & 8",
    difficulty: "medium",
    isOfficial: true,
    questions: [
      {
        id: "q12-1",
        prompt: "Identify the oldest oil-producing region in India, operating since 1901 in Assam.",
        options: ["Mumbai High", "Digboi", "Ankleshwar", "Kalol"],
        correctAnswer: "Digboi",
        targetCoords: { lat: 27.3800, lng: 95.6300 },
        explanation: "Digboi in Tinsukia district of Assam is the oldest continuously operating oil well and refinery in India.",
      },
      {
        id: "q12-2",
        prompt: "Which major port on the east coast was developed to handle iron ore exports from Bailadila mines and has a natural landlocked harbour?",
        options: ["Paradip", "Visakhapatnam", "Chennai", "Tuticorin"],
        correctAnswer: "Visakhapatnam",
        targetCoords: { lat: 17.6868, lng: 83.2185 },
        explanation: "Visakhapatnam is a landlocked natural port protected by Dolphin's Nose hill, exporting Bailadila iron ore.",
      },
      {
        id: "q12-3",
        prompt: "Which prominent coalfield in Jharkhand provides prime coking coal to Jamshedpur and Bokaro steel plants?",
        options: ["Jharia", "Singrauli", "Neyveli", "Talcher"],
        correctAnswer: "Jharia",
        targetCoords: { lat: 23.7400, lng: 86.4100 },
        explanation: "Jharia in Dhanbad district is India's most important reservoir of metallurgical grade coking coal.",
      },
      {
        id: "q12-4",
        prompt: "Which is the major tidal port located at the head of Gulf of Kachchh in Gujarat?",
        options: ["Marmagao", "Kandla (Deendayal)", "JNPT Nhava Sheva", "Cochin"],
        correctAnswer: "Kandla (Deendayal)",
        targetCoords: { lat: 23.0033, lng: 70.2181 },
        explanation: "Kandla port is a tidal port built to serve the vast northwestern hinterland.",
      },
    ],
  },
];
